AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda function to handle CPF input

Resources:
    validateCustomer:
        Type: AWS::Serverless::Function
        Properties:
            Handler: dist/index.handler
            Runtime: nodejs18.x
            Timeout: 30
